services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-app
    working_dir: /var/www/
    # Conditional volume mounting based on environment variable
    volumes:
      - ../src:/var/www
      - ./php/php.ini-${APP_ENV}:/usr/local/etc/php/php.ini  # Mount environment-specific php.ini

  nginx:
    image: nginx:1.25.3-alpine
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
