services:
  php-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-app
    working_dir: /var/www/
    ports:
      - 50500:9000
    # Conditional volume mounting based on environment variable
    volumes:
      - ../src:/var/www
    # Mount environment-specific php.ini
      - ./php/php.ini-${APP_ENV}:/usr/local/etc/php/php.ini
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports:
      - 50501:8080
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  pgsql:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: pgsql
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    shm_size: 2GB
    ports:
      - 50502:${DB_PORT}
    environment:
      POSTGRES_INITDB_ARGS_FILE: "/run/secrets/db_init_args"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_WALDIR: ${POSTGRES_INITDB_WALDIR}
      PGDATA: ${PGDATA}
    secrets:
      - db_init_args
      - db_password

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      # https://github.com/pgadmin-org/pgadmin4/blob/master/docs/en_US/container_deployment.rst
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_LISTEN_PORT: 65500
    ports:
      - 50503:65500
    secrets:
      - pgadmin_password
    depends_on:
      - pgsql

# Docker Storage
volumes:
  dbdata:
  pgadmin_data:

secrets:
  db_password:
     file: ./secrets/.pg_password.env
  db_init_args:
     file: ./secrets/.pg_init_args.env
  pgadmin_password:
     file: ./secrets/.pgadmin_password.env
